FROM python:3.8-slim-buster

RUN apt update && \
apt install -y libgl1 sudo gcc libglib2.0-0 git-all

WORKDIR /demo
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip && \
pip3 install -r requirements.txt

# install norfair
WORKDIR /
RUN git clone https://github.com/tryolabs/norfair.git ./norfair/ && \
    pip3 install ./norfair/

WORKDIR /demo/src/ 