FROM python:3.8-slim-buster

WORKDIR /

RUN apt update && \
apt install -y libgl1 sudo gcc libglib2.0-0 git-all wget

RUN pip3 install --upgrade pip && \
pip3 install -r https://raw.githubusercontent.com/WongKinYiu/yolov7/main/requirements.txt

RUN git clone https://github.com/tryolabs/norfair.git ./norfair/ && \
pip3 install ./norfair/

WORKDIR /demo/src/