FROM python:3.8-slim-buster

WORKDIR /demo
RUN apt update
# RUN apt install -y ffmpeg libsm6 libxext6
RUN apt install -y libgl1 sudo gcc libglib2.0-0 git-all
# RUN apt install -y libgl1-mesa-dri
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip; \
    pip3 install -r requirements.txt

RUN git clone https://github.com/tryolabs/norfair.git ./norfair/ && cd ./norfair/
RUN pip3 install ./norfair/

WORKDIR /demo/src/