openpose:
  dir: <openpose_directory>/openpose
  logging_level: 3
  output_resolution: -1x-1 # 320x176
  net_resolution: -1x768 # 320x176
  model_pose: BODY_25
  alpha_pose: 0.6
  scale_gap: 0.3
  scale_number: 1
  render_threshold: 0.05
  num_gpu_start: 0  # If GPU version is built, and multiple GPUs are available, set the ID here
  disable_blending: false
